name: k8s-workload.yml

on:
  workflow_dispatch: ~
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build_metadata:
    uses: nodis-com-br/gha-workflows/.github/workflows/build_metadata.yaml@master
  test_code:
    uses: nodis-com-br/gha-workflows/.github/workflows/testing.yaml@master
    needs:
      - build_metadata
    secrets:
      openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
      vault_addr: ${{ secrets.VAULT_ADDR }}
      vault_approle_role_id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault_approle_secret_id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
  publish_artifact:
    uses: nodis-com-br/gha-workflows/.github/workflows/publish_private_image.yaml@master
    needs:
      - build_metadata
  deploy_artifact:
    uses: nodis-com-br/gha-workflows/.github/workflows/deploy_workload.yaml@master
    needs:
      - publish_artifact
    secrets:
      openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
      vault_addr: ${{ secrets.VAULT_ADDR }}
      vault_approle_role_id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault_approle_secret_id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
  revert_bump:
    uses: nodis-com-br/gha-workflows/.github/workflows/revert_bump.yaml@master
    needs:
      - publish_artifact
    if: always()
    with:
      build_result: ${{ needs.publish_artifact.result }}