name: helm-chart

on:
  workflow_dispatch: ~
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
      
jobs:
  get_metadata:
    uses: nodis-com-br/gha-workflows/.github/workflows/get-metadata.yaml@master
  publish_artifact:
    uses: nodis-com-br/gha-workflows/.github/workflows/publish-helm-chart.yaml@master
    needs:
      - get_metadata
    secrets:
      charts_addr: ${{ secrets.CHARTS_ADDR }}
  revert_bump:
    uses: nodis-com-br/gha-workflows/.github/workflows/revert-bump.yaml@master
    needs:
      - publish_artifact
    if: always()
    with:
      build_result: ${{ needs.publish_artifact.result }}